// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCurrentStationInfo():Promise<Array<main.StationInfo>>;

export function Greet(arg1:string):Promise<string>;

export function PowerOffAllStations():Promise<void>;

export function PowerOffStation(arg1:string):Promise<void>;

export function PowerOnAllStations():Promise<void>;

export function PowerOnStation(arg1:string):Promise<void>;

export function ScanAndFetchStations():Promise<Array<main.StationInfo>>;
