// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {station} from '../models';

export function CheckAllStationStatuses():Promise<Array<station.StationInfo>>;

export function GetCurrentStationInfo():Promise<Array<station.StationInfo>>;

export function Greet(arg1:string):Promise<string>;

export function IsScanning():Promise<boolean>;

export function PowerOffAllStations():Promise<void>;

export function PowerOffStation(arg1:string):Promise<void>;

export function PowerOnAllStations():Promise<void>;

export function PowerOnStation(arg1:string):Promise<void>;

export function RenameStation(arg1:string,arg2:string):Promise<void>;

export function SaveConfig():Promise<void>;

export function ScanAndFetchStations():Promise<Array<station.StationInfo>>;
