// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentStationInfo() {
  return window['go']['main']['App']['GetCurrentStationInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PowerOffAllStations() {
  return window['go']['main']['App']['PowerOffAllStations']();
}

export function PowerOffStation(arg1) {
  return window['go']['main']['App']['PowerOffStation'](arg1);
}

export function PowerOnAllStations() {
  return window['go']['main']['App']['PowerOnAllStations']();
}

export function PowerOnStation(arg1) {
  return window['go']['main']['App']['PowerOnStation'](arg1);
}

export function ScanAndFetchStations() {
  return window['go']['main']['App']['ScanAndFetchStations']();
}
